stages:
  - buildandpush
  - deploy

variables:
  IMAGE_NAME: "$HARBOR_REGISTRY/internal/ipam"

buildandpush:
  stage: buildandpush
  image: docker:latest
  tags:
    - docker
  script:
    - echo "$HARBOR_PASSWORD" | docker login $HARBOR_REGISTRY -u "$HARBOR_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
    - docker tag $IMAGE_NAME:$IMAGE_TAG $HARBOR_REGISTRY/public/ipam:$IMAGE_TAG
    - docker tag $IMAGE_NAME:$IMAGE_TAG $HARBOR_REGISTRY/public/ipam:latest
    - docker push $HARBOR_REGISTRY/public/ipam:$IMAGE_TAG
    - docker push $HARBOR_REGISTRY/public/ipam:latest

deploy:
  stage: deploy
  tags:
    - k3s-lan-01
  script:
    - sudo kubectl replace -f deployment.yml --grace-period=60 --force