apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipam
  namespace: ipam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam
  template:
    metadata:
      labels:
        app: ipam
    spec:
      containers:
        - name: ipam
          image: ghcr.io/jdb-net/ipam:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: "ipam"
          env:
            - name: SECRET_KEY
              value: "41TbN7v5peFLZPrdwSCc64J3mjmiUk5fkVWsmb2m"
            - name: MYSQL_HOST
              value: "10.10.25.4"
            - name: MYSQL_USER
              value: "ipam"
            - name: MYSQL_PASSWORD
              value: "WXPmo05sGCfjGe"
            - name: MYSQL_DATABASE
              value: "ipam"
---
apiVersion: v1
kind: Service
metadata:
  name: ipam-ingress-service
  namespace: ipam
spec:
  selector:
    app: ipam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipam-ingress
  namespace: ipam
spec:
  rules:
  - host: ipam.jdb143.uk
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: ipam-ingress-service
            port:
              number: 80